# Generated by Django 5.0.6 on 2024-07-08 20:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0002_servicio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('fechaCompra', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='id',
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(default='Descripción del servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='idServicio',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default='Nombre del servicio', max_length=50),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='servicio',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='detalle_boleta',
            fields=[
                ('id_detalle_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.BigIntegerField()),
                ('id_boleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Reserva.boleta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserva.servicio')),
            ],
        ),
    ]
